{"uuid": "b01f5eac-26a4-458b-96e1-df58f2088881", "children": ["957cddb4-360c-4a2c-bb1b-55e1f4a4e605"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "ValueError: no option named '--appium_port'\n", "trace": "  File \"D:\\Program Files\\python3x\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\23850\\AppData\\Roaming\\Python\\Python39\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\23850\\AppData\\Roaming\\Python\\Python39\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Program Files\\JetBrains\\python\\auto_app_test\\test_cases\\app\\conftest.py\", line 9, in driver\n    appium_port = pytestconfig.getoption('--appium_port')\n  File \"C:\\Users\\23850\\AppData\\Roaming\\Python\\Python39\\site-packages\\_pytest\\config\\__init__.py\", line 1499, in getoption\n    raise ValueError(f\"no option named {name!r}\") from e\n"}, "start": 1660289012618, "stop": 1660289012618}], "start": 1660289012618, "stop": 1660289012811}